version: "3"
services:

  pgadmin:
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    restart: unless-stopped
    logging:
      driver: none
    volumes:
      - "/data/pgadmin:/root/.pgadmin"

  postgres:
    container_name: WorkForceDB
    environment:
      POSTGRES_DB: work_force_db
      POSTGRES_PASSWORD: "admin#123"
      POSTGRES_USER: admin
    image: "postgres:9.5"
    ports:
      - "127.0.0.1:5433:5432"
    restart: unless-stopped
    volumes:
      - "pgdata:/var/lib/postgresql/data/"

  django:
    build: ./
    command: "python3 manage.py runserver 0.0.0.0:8000"
    container_name: WorkForce
    entrypoint: /workforce/entrypoint.sh
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ".:/workforce"

#  client:
#    build:
#      context: ./angular
#      dockerfile: ./Dockerfile
#    command: ["npm", "start"]
#    ports:
#      - "4200:4200"
#    volumes:
#      - "./angular:/usr/src/app"
#
#  nginx:
#    build:
#      context: ./nginx/
#      dockerfile: ./Dockerfile
#    restart: always
#    ports:
#      - "8089:80"
#    volumes:
#      - "./angular/dist/WorkForce:/usr/src/app"
#      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
#      - ".:/workforce"
#    depends_on:
#      - django
#      - client

volumes:
  pgdata: ~
