# Generated by Django 2.1.2 on 2018-10-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('liquor_type', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
