# Generated by Django 2.1.2 on 2018-10-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_test_app', '0002_liquor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='high_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='liquor',
            old_name='liquor_type',
            new_name='type',
        ),
    ]
