# Generated by Django 2.1.4 on 2019-01-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_req_refund',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
