# Generated by Django 2.1.4 on 2019-01-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_line_is_req_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='is_req_refund',
            field=models.CharField(default='0', help_text='0=No, 1=Yes', max_length=4),
        ),
    ]
