# Generated by Django 2.1.4 on 2019-01-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190110_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dispatched',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='line',
            name='req_refund_status',
            field=models.CharField(default='0', help_text='0=No Action, 1=User requested for refund, 2=Admin accepted refund, 3=Admin canceled refund, 4=Order has been dispatch', max_length=4),
        ),
    ]
