# Generated by Django 2.1.4 on 2019-01-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190115_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refund_all',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
