# Generated by Django 2.1.4 on 2019-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_is_refund_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='req_refund_status',
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_dispatched',
            field=models.CharField(default='0', help_text='0=No, 1=Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_refund_all',
            field=models.CharField(default='0', help_text='0=No, 1=Yes', max_length=10),
        ),
    ]
