# Generated by Django 2.1.7 on 2019-02-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190220_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='user_phone',
        ),
    ]
