# Generated by Django 2.1.7 on 2019-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190221_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
