# Generated by Django 2.1.7 on 2019-02-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='device_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
