# Generated by Django 2.1.7 on 2019-02-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190225_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_counter',
            field=models.IntegerField(default=0),
        ),
    ]
