# Generated by Django 2.1.7 on 2019-02-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_otp_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_type', models.CharField(max_length=20, unique=True)),
                ('ambulance_data', models.TextField()),
                ('base_fare', models.FloatField()),
                ('ambulance_minprice', models.FloatField()),
                ('ambulance_maxprice', models.FloatField()),
                ('cost_per_minute', models.FloatField()),
                ('cost_per_km', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
