# Generated by Django 2.1.7 on 2019-02-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ambulancetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancetype',
            name='ambulance_maxprice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ambulancetype',
            name='ambulance_minprice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ambulancetype',
            name='base_fare',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ambulancetype',
            name='cost_per_km',
            field=models.FloatField(verbose_name=0.0),
        ),
        migrations.AlterField(
            model_name='ambulancetype',
            name='cost_per_minute',
            field=models.FloatField(verbose_name=0.0),
        ),
    ]
