# Generated by Django 2.1.7 on 2019-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190227_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.SmallIntegerField(default=0),
        ),
    ]
