# Generated by Django 2.1.7 on 2019-02-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_secrect_key',
            new_name='otp_secret_key',
        ),
    ]
