    # Ansible mysql_secure_installation playbook
---
- name: Install Packages
  hosts: web1
  become: yes
  vars:
    root_db_password: karakira

  tasks: 
    - name: delete anonymous MySQL server user for {{ ansible_hostname }}
      action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
    
    - name: delete anonymous MySQL server user for localhost
      action: mysql_user user="" state="absent"
    
    - name: remove the MySQL test database
      action: mysql_db db=test state=absent
      
      
    # 'localhost' needs to be the last item for idempotency, see
    # http://ansible.cc/docs/modules.html#mysql-user   
    - name: Change root user password on first run
      mysql_user: login_user=root
                  login_password=''
                  name=root
                  password={{ mysql_root_password }}
                  priv=*.*:ALL,GRANT
                  host={{ item }}
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost