# Generated by Django 2.2 on 2019-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on', models.DateTimeField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('title_image', models.ImageField(blank=True, upload_to='blog/title_images/%Y/%m/%d')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=300)),
            ],
        ),
    ]
