# Generated by Django 2.2 on 2019-05-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190510_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
