# Generated by Django 2.2.4 on 2019-08-09 14:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/%Y/%m/%d')),
                ('analysis_json', jsonfield.fields.JSONField()),
            ],
        ),
    ]
