# Generated by Django 2.2.4 on 2019-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestorage',
            name='client_ip',
            field=models.CharField(default='', max_length=20),
        ),
    ]
