# Generated by Django 2.1.4 on 2019-01-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
