# Generated by Django 2.1.4 on 2019-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190109_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='is_req_refund',
        ),
        migrations.AddField(
            model_name='line',
            name='req_refund_status',
            field=models.CharField(default='0', help_text='0=No Action, 1=User requested for refund, 2=Admin accepted refund, 3=Admin canceled refund', max_length=4),
        ),
    ]
